In [2]:
# Use NumPy arrays to perform vector addition, dot products, and reshape operations.

import numpy as np

arr1 = np.array([1, 2, 3, 7, 8, 9])
arr2 = np.array([4, 5, 6, 3, 5, 2])

addition = arr1 + arr2
print("Vector Addition:")
print(addition)

dot_prod = np.dot(arr1, arr2)
print("\nDot Product:")
print(dot_prod)

reshaped = arr1.reshape(2, 3)
print("\nBefore Reshaping:")
print(arr1)
print("\nAfter Reshaping:")
print(reshaped)

Vector Addition:
[ 5  7  9 10 13 11]

Dot Product:
111

Before Reshaping:
[1 2 3 7 8 9]

After Reshaping:
[[1 2 3]
 [7 8 9]]
